# Generated by Django 3.1.9 on 2021-05-19 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioId', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200)),
                ('paterno', models.CharField(max_length=200)),
                ('materno', models.CharField(max_length=100)),
                ('registro_fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
