# Generated by Django 3.1.9 on 2021-05-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.IntegerField(default=0),
        ),
    ]
